=== VEuPathDB/ApiCommonModel/Model/lib/xml/datasetPresenters/datasetPresenters.dtd
<!ELEMENT datasetPresenters (datasetPresenter+, internalDataset*)>
 <!ELEMENT datasetPresenter (displayName, shortDisplayName?, displayCategory?, summary, description, usage?, protocol?, caveat?, acknowledgement?, releasePolicy?, primaryContactId, contactId*, link*, pubmedId*, wdkReference*, templateInjector?)>
 <!ELEMENT displayName (#PCDATA)>
 <!ELEMENT shortDisplayName (#PCDATA)>
 <!ELEMENT displayCategory (#PCDATA)>
 <!ELEMENT summary (#PCDATA)>
 <!ELEMENT description (#PCDATA)>
 <!ELEMENT usage (#PCDATA)>
 <!ELEMENT protocol (#PCDATA)>
 <!ELEMENT caveat (#PCDATA)>
 <!ELEMENT acknowledgement (#PCDATA)>
 <!ELEMENT releasePolicy (#PCDATA)>
 <!ELEMENT primaryContactId (#PCDATA)>
 <!ELEMENT contactId (#PCDATA)>
 <!ELEMENT link (text?,url)>
 <!ELEMENT text (#PCDATA)>
 <!ELEMENT url (#PCDATA)>
 <!ELEMENT pubmedId (#PCDATA)>
 <!ELEMENT wdkReference (#PCDATA)>
 <!ELEMENT templateInjector (prop*)>
 <!ELEMENT prop (#PCDATA)>
 <!ELEMENT internalDataset (#PCDATA)>

<!ATTLIST datasetPresenter name CDATA #REQUIRED>
<!ATTLIST datasetPresenter projectName CDATA #IMPLIED>
<!ATTLIST datasetPresenter buildNumberIntroduced CDATA #IMPLIED>
<!ATTLIST datasetPresenter datasetNamePattern CDATA #IMPLIED>
<!ATTLIST datasetPresenter override CDATA #IMPLIED>
<!ATTLIST wdkReference
          recordClass CDATA #REQUIRED
          type CDATA #REQUIRED
          name CDATA #REQUIRED
>
<!ATTLIST templateInjector className CDATA #REQUIRED>
<!ATTLIST internalDataset name CDATA #REQUIRED>
<!ATTLIST internalDataset datasetNamePattern CDATA #IMPLIED>
<!ATTLIST prop name CDATA #REQUIRED>

=== VEuPathDB/ApiCommonModel/Model/lib/xml/datasetPresenters/HostDB.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="datasetPresenters.xslt"?>
<!DOCTYPE datasetPresenters SYSTEM "datasetPresenters.dtd">
<datasetPresenters>

  <datasetPresenter name="DUMMY"
                    projectName="HostDB"
                    >
    <displayName></displayName>
    <shortDisplayName></shortDisplayName>
    <displayCategory></displayCategory>
    <summary></summary>
    <description></description>
    <protocol></protocol>
    <caveat></caveat>
    <acknowledgement></acknowledgement>
    <releasePolicy></releasePolicy>
    <primaryContactId>TODO</primaryContactId>
    <link>
      <text></text>
      <url></url>
    </link>
    <pubmedId></pubmedId>
  </datasetPresenter>

  <datasetPresenter name="hsapREF_primary_genome_RSRC"
                    projectName="HostDB"
                    buildNumberIntroduced="18"
                    >
    <displayName>Homo sapiens Genome</displayName>
    <shortDisplayName>Human Genome</shortDisplayName>
    <displayCategory></displayCategory>
    <summary></summary>
    <description></description>
    <protocol></protocol>
    <caveat></caveat>
    <acknowledgement></acknowledgement>
    <releasePolicy></releasePolicy>
    <primaryContactId></primaryContactId>
    <link>
      <text>This directory contains the Feb. 2009 assembly of the human genome (hg19,
			GRCh37 Genome Reference Consortium Human Reference 37 (GCA_000001405.1))
			in one gzip-compressed FASTA file per chromosome.
			</text>
      <url>ftp://hgdownload.cse.ucsc.edu/goldenPath/hg19/chromosomes/</url>
    </link>
    <pubmedId></pubmedId>
  </datasetPresenter>

  <datasetPresenter name="hsapREF_Gregory_ME49_mRNA_rnaSeq_RSRC"
                    projectName="HostDB"
                    buildNumberIntroduced="18"
                    >
    <displayName>Gregory T. gondii ME49 Tachyzoite Post Infection Time Series </displayName>
    <shortDisplayName>Time Series</shortDisplayName>
    <displayCategory></displayCategory>
    <summary></summary>
    <description></description>
    <protocol></protocol>
    <caveat></caveat>
    <acknowledgement></acknowledgement>
    <releasePolicy></releasePolicy>
    <primaryContactId>gregory.grant</primaryContactId>
    <link>
      <text></text>
      <url></url>
    </link>
    <pubmedId></pubmedId>
  </datasetPresenter>

 <!-- <internalDataset name="hsapREF_primary_genome_RSRC"/> -->
 <!-- <internalDataset name="hsapREF_Gregory_ME49_mRNA_rnaSeq_RSRC"/> -->
 <internalDataset name="hsapREF_ucscId_NAFeature_aliases_RSRC"/>
 <internalDataset name="hsapREF_havanaGeneId_NAFeature_aliases_RSRC"/>
 <internalDataset name="hsapREF_havanaTranscriptId_NAFeature_aliases_RSRC"/>
 <internalDataset name="hsapREF_transcriptId_NAFeature_aliases_RSRC"/>
 <internalDataset name="hsapREF_genome_gencode_RSRC"/>

</datasetPresenters>
